#!/bin/sh

set -e

cd "$(dirname "$0")/.."

. ./.env

echo "==> Building supporting containers."
docker build -f .docker/db-cli/Dockerfile --force-rm -t "${COMPOSE_PROJECT_NAME}"/db-cli .docker/db-cli/
docker build -f .docker/php-cli/Dockerfile --force-rm -t "${COMPOSE_PROJECT_NAME}"/php-cli .docker/php-cli/

echo "==> Builing service containers."
docker-compose build --force-rm
