---

- name: set default postfix mailname and mailer type
  debconf: name=postfix question="postfix/{{ item.key }}" vtype='string' value="{{ item.value }}"
  with_items: "{{ postfix_configuration }}"

- name: install {{ postfix_packages|join(", ") }} for mail delivery
  apt: name={{ item }} update_cache=yes cache_valid_time={{ provision_apt_update_cache_cache_valid_time }}
  with_items: "{{ postfix_packages }}"
