---

- name: write container
  command: dd if=/dev/zero of={{ swap_path }} bs={{ swap_base }} count={{ swap_count }} creates={{ swap_path }}
  when: ansible_swaptotal_mb < {{ swap_minimum_mb }}

- name: make partition
  shell: /sbin/mkswap {{ swap_path }}
  when: ansible_swaptotal_mb < {{ swap_minimum_mb }}

- name: enable partition
  shell: /sbin/swapon {{ swap_path }}
  when: ansible_swaptotal_mb < {{ swap_minimum_mb }}
