sudo: false
dist: trusty

addons:
  apt:
    packages:
    - libxml2-utils
    - php5-curl
    - xsltproc

before_install:
  - export PATH=$HOME/.local/bin:$PATH
  # Install Ansible.
  - pip install -q --user `whoami` ansible

language: php
php:
  - "5.5"

script:
  - find . -path "*/vantomas/Resources/*.xml" -exec xmllint --noout {} \;
  - find . -path "*/vantomas/Resources/*.xlf" -exec xmllint --noout {} \;
  - find . -path "*/vantomas/Classes/*.php" -exec php -l {} \;
  - find . -path "*/vantomas/Tests/*.php" -exec php -l {} \;
  - mkdir -p .ansible/logs
  - ansible-playbook .ansible/playbooks/ci.yml
