version: '2'

volumes:
  db-storage:
    driver: local

services:
  db:
    build: .docker/db/
    image: vantomas/db
    env_file: .docker/db/.env
    volumes:
      - db-storage:/var/lib/mysql

  php:
    build: .docker/php/
    image: vantomas/php
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db

  httpd:
    build: .docker/httpd/
    image: vantomas/httpd
    volumes:
      - .:/app
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
    depends_on:
      - php
