---

- name: create CA key
  command: >
    openssl
    genrsa -des3
    -out {{ ssl_client_auth_output_prefix }}CA.key
    -passout pass:{{ ssl_client_auth_ca_password }}
    4096

- name: create CA cert
  command: >
    openssl
    req -new -x509 -days 365
    -key {{ ssl_client_auth_output_prefix }}CA.key
    -out {{ ssl_client_auth_output_prefix }}CA.crt
    -subj '{{ ssl_client_auth_ca_subject }}'
    -passin pass:{{ ssl_client_auth_ca_password }}

- name: create stages keys
  command: >
    openssl
    genrsa -des3
    -out {{ ssl_client_auth_output_prefix }}{{ item.name }}.key
    -passout pass:{{ item.password }}
    1024
  with_items: "{{ ssl_client_auth_certs_stages }}"

- name: create password less stage keys
  command: >
    openssl
    rsa
    -in {{ ssl_client_auth_output_prefix }}{{ item.name }}.key
    -out {{ ssl_client_auth_output_prefix }}{{ item.name }}_nopass.key
    -passin pass:{{ item.password }}
  with_items: "{{ ssl_client_auth_certs_stages }}"

- name: create stage cert requests
  command: >
    openssl
    req -new
    -key {{ ssl_client_auth_output_prefix }}{{ item.name }}.key
    -out {{ ssl_client_auth_output_prefix }}{{ item.name }}.csr
    -subj '{{ item.subject }}'
    -passin pass:{{ item.password }}
  with_items: "{{ ssl_client_auth_certs_stages }}"

- name: self-sign stages certs
  command: >
    openssl
    x509 -req -days 365
    -in {{ ssl_client_auth_output_prefix }}{{ item.name }}.csr
    -CA {{ ssl_client_auth_output_prefix }}CA.crt
    -CAkey {{ ssl_client_auth_output_prefix }}CA.key
    -set_serial {{ item.serial }}
    -out {{ ssl_client_auth_output_prefix }}{{ item.name }}.crt
    -passin pass:{{ ssl_client_auth_ca_password }}
  with_items: "{{ ssl_client_auth_certs_stages }}"

- name: create user keys
  command: >
    openssl
    genrsa -des3
    -out {{ ssl_client_auth_output_prefix }}{{ item.name }}.key
    -passout pass:{{ item.password }}
    1024
  with_items: "{{ ssl_client_auth_certs_users }}"

- name: create user cert requests
  command: >
    openssl
    req -new
    -key {{ ssl_client_auth_output_prefix }}{{ item.name }}.key
    -out {{ ssl_client_auth_output_prefix }}{{ item.name }}.csr
    -subj '{{ item.subject }}'
    -passin pass:{{ item.password }}
  with_items: "{{ ssl_client_auth_certs_users }}"

- name: sign user certs
  command: >
    openssl
    x509 -req -days 365
    -in {{ ssl_client_auth_output_prefix }}{{ item.name }}.csr
    -CA {{ ssl_client_auth_output_prefix }}CA.crt
    -CAkey {{ ssl_client_auth_output_prefix }}CA.key
    -set_serial {{ item.serial }}
    -out {{ ssl_client_auth_output_prefix }}{{ item.name }}.crt
    -passin pass:{{ ssl_client_auth_ca_password }}
  with_items: "{{ ssl_client_auth_certs_users }}"

- name: export user pkcs12 certs
  command: >
    openssl
    pkcs12 -export -nodes
    -inkey {{ ssl_client_auth_output_prefix }}{{ item.name }}.key
    -name "{{ item.pkcs12_friendly_name }}"
    -in {{ ssl_client_auth_output_prefix }}{{ item.name }}.crt
    -certfile {{ ssl_client_auth_output_prefix }}CA.crt
    -out {{ ssl_client_auth_output_prefix }}{{ item.name }}.p12
    -passin pass:{{ item.password }}
    -passout pass:{{ item.export_password }}
  with_items: "{{ ssl_client_auth_certs_users }}"
