---

- name: clear database cache
  shell: mysql -u{{ release_database_remote_username }} -p{{ release_database_remote_password }} -h{{ release_database_remote_host }} {{ release_database_remote_name }} -e "{{ item }}"
  with_items: deploy_post_cache_database
  when: clear_cache|default("yes") or clear_cache_database|default("no")
