---

- name: prepare directory structure
  file: >
    dest={{ deploy_to }}/{{ item.dest }}
    recurse=yes
    mode={{ deploy_post_dir_mode }}
    owner={{ deploy_post_dir_user }}
    group={{ deploy_post_dir_group }}
    state={{ item.state }}
  with_items: deploy_post_directories

- name: prepare directories index.html
  file: dest={{ deploy_to }}/{{ item.dest }} state={{ item.state }}
  with_items: deploy_post_files

- include: cache-files.yml

- include: cache-database.yml
