---

- name: download
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir={{ composer_bin|dirname }} --filename=composer creates={{ composer_bin|basename }}

- name: stat binary
  stat: path="{{ composer_bin }}"
  register: current_composer

- name: get update moment timestamp
  shell: date --date='{{ composer_update_days }} days ago' +'%s'
  register: composer_update_date
  changed_when: false

- name: update
  composer: command=self-update no_dev={{ composer_no_dev }} optimize_autoloader={{ composer_optimize_autoloader }} working_dir={{ composer_bin|dirname }}
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ composer_bin|dirname }}"
  when: composer_update_date.stdout|int > current_composer.stat.mtime|int

- name: install dependencies
  composer: command=install no_dev={{ composer_no_dev }} optimize_autoloader={{ composer_optimize_autoloader }} working_dir={{ working_dir }}
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ composer_bin|dirname }}"

- name: dump autoload
  command: ./composer dump-autoload --optimize --working-dir={{ working_dir }} chdir={{ working_dir }}
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ composer_bin|dirname }}"
