---

- hosts: development
  sudo: yes

  vars:
    # 7 days
    provision_apt_update_cache_cache_valid_time: 604800

  roles:
    - { role: swap, tags: ["swap"] }
    - { role: nginx, tags: ["configuration-update"] }
    - { role: mysql, tags: ["initialize-database"] }
    - { role: php, tags: ["configuration-update"] }
    - { role: tools }
    - { role: bytepark-release }
    - { role: postfix }
    - { role: init-database, tags: ["initialize-database"] }
