---

- hosts: development

  roles:
    - {
        role: deploy-check,
        tags: ["deploy", "check"]
      }
    - {
        role: prepare-app,
        tags: ["cleanup"]
      }
    - {
        role: composer,
        composer_no_dev: yes,
        tags: ["package-manager", "cleanup"]
      }
    - {
        role: notification,
        notification_title: "Composer",
        notification_body: "Finished installing production dependencies.",
        tags: ["package-manager", "cleanup"]
      }
    - {
        role: node,
        tags: ["package-manager"]
      }
    - {
        role: notification,
        notification_title: "Node.js",
        notification_body: "Finished installing node.js dependencies.",
        tags: ["package-manager"]
      }
    - {
        role: npm-run-script,
        scripts: ["grunt-build:{{ grunt_environment }}"]
      }
    - {
        role: deploy-app-version,
        tags: ["app-version"]
      }

- hosts: all:!development

  roles:
    - {
        role: prepare-htpasswd,
        working_dir: "{{ deploy_to }}",
        tags: ["deploy", "pre"]
      }
    - {
        role: deploy-rsync,
        tags: ["deploy", "rsync"]
      }
    - {
        role: notification,
        notification_title: "Deploy",
        notification_body: "Finished deployment.",
        tags: ["deploy"]
      }
    - {
        role: deploy-post,
        tags: ["deploy", "post"]
      }

- hosts: development

  roles:
    - {
        role: composer,
        tags: ["package-manager", "cleanup"]
      }
    - {
        role: notification,
        notification_title: "Composer",
        notification_body: "Finished installing development dependencies.",
        tags: ["package-manager", "cleanup"]
      }
