---

- hosts: all

  roles:
    - {
        role: composer,
        composer_no_dev: yes,
        when: ansible_env.CI is undefined or not ansible_env.CI,
        tags: ["package-manager", "cleanup"]
      }
    - {
        role: node,
        when: ansible_env.CI is undefined or not ansible_env.CI,
        tags: ["package-manager"]
      }
    - {
        role: npm-run-script,
        when: ansible_env.CI is undefined or not ansible_env.CI,
        scripts: ["grunt-build:{{ grunt_environment|default(ansible_env.TRAVIS_BRANCH) }}"]
      }
    - {
        role: deploy-app-version,
        tags: ["app-version", "prepare", "compress"]
      }
    - {
        role: create-archive,
        tags: ["prepare", "compress"]
      }
