---

- name: install PHP
  apt: name={{ item }} update_cache=yes cache_valid_time={{ provision_apt_update_cache_cache_valid_time }}
  with_items: "{{ php_packages }}"

- name: inject PHP5 configuration
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items: "{{ php_configuration }}"
  notify:
    - restart php

- name: disable xdebug for cli
  file: path=/etc/php5/cli/conf.d/20-xdebug.ini state=absent

- name: remove default php5-fpm pool
  file: path=/etc/php5/pool.d/www.conf state=absent
  notify:
    - restart php
    - restart httpd
