---

- name: clone bytepark release tool
  git: repo=https://github.com/bytepark/release.git dest=/opt/bytepark-release version={{ bytepark_release.version }}

- name: link and install bytepark release tool
  file: path={{ item.path }} src={{ item.src }} state=link
  with_items:
    - { path: '/opt/release', src: '/opt/bytepark-release' }
    - { path: '/usr/local/bin/release', src: '/opt/bytepark-release/release.sh' }
