---

- name: install tools
  apt: name={{ item }} update_cache=yes cache_valid_time={{ provision_apt_update_cache_cache_valid_time }}
  with_items: "{{ tools_packages }}"

- name: updating /etc/hosts for live domain
  lineinfile: dest=/etc/hosts regexp="{{ item.regexp }}" line="{{ item.line }}"
  with_items: "{{ tools_etc_hosts }}"
  when: tools_update_etc_hosts

- name: install ansible
  pip: name=ansible

# this fixes an issue with scp style github addresses
# @see https://github.com/travis-ci/travis.rb/issues/342
#
- name: install addressable gem
  gem: name=addressable version=2.3.8 state=present

- name: install travis gem
  gem: name=travis state=present

- name: update bashrc - auto change directory after login
  lineinfile: >
    dest={{ tools_bashrc }}
    regexp="^cd {{ tools_autocd_target }}$"
    line="cd {{ tools_autocd_target }}"
    stage=present
  become: no
  when: tools_autocd

- name: update bashrc - force color prompt
  lineinfile: >
    dest={{ tools_bashrc }}
    regexp="^#force_color_prompt=yes"
    line="force_color_prompt=yes"
    state=present
  become: no
  when: tools_force_color_prompt
