---

- name: install tools
  apt: name={{ item }} update_cache=yes cache_valid_time={{ provision_apt_update_cache_cache_valid_time }}
  with_items: "{{ tools_packages }}"

- name: updating /etc/hosts for live domain
  lineinfile: dest=/etc/hosts regexp="{{ item.regexp }}" line="{{ item.line }}"
  with_items: "{{ tools_etc_hosts }}"
  when: tools_update_etc_hosts

- name: install ansible
  pip: name=ansible

- name: update bashrc for auto change directory after login
  lineinfile: dest={{ tools_autocd_bashrc }} regexp="^cd {{ tools_autocd_target }}$" line="cd {{ tools_autocd_target }}"
  become: no
  when: tools_autocd
