---

- name: setup nvm
  shell: curl https://raw.githubusercontent.com/creationix/nvm/v{{ node_nvm_version }}/install.sh | NVM_DIR={{ node_nvm_bin|dirname }} bash creates={{ node_nvm_bin }} executable=/bin/bash

- name: check installed version
  shell: source {{ node_nvm_bin }} 2>/dev/null; nvm current chdir={{ working_dir }} executable=/bin/bash
  ignore_errors: yes
  register: current_node

- name: install
  shell: source {{ node_nvm_bin }}; nvm install chdir={{ working_dir }} executable=/bin/bash
  when: current_node.stdout == "none"

- name: update npm
  shell: source {{ node_nvm_bin }}; npm install -g npm@{{ node_npm_version }} chdir={{ working_dir }} executable=/bin/bash
  when: current_node.stdout == "none" and node_update_npm

- name: install packages
  shell: source {{ node_nvm_bin }}; npm install chdir={{ working_dir }} executable=/bin/bash
