---

- name: setup nvm
  shell: curl https://raw.githubusercontent.com/creationix/nvm/v{{ node.nvm_version }}/install.sh | NVM_DIR={{ node.nvm_bin|dirname }} bash creates={{ node.nvm_bin }}

- name: check installed version
  shell: source {{ node.nvm_bin }} 2>/dev/null; nvm current chdir={{ project_dir }} executable=/bin/bash
  ignore_errors: yes
  register: current_node

- name: install
  shell: source {{ node.nvm_bin }}; nvm install chdir={{ project_dir }} executable=/bin/bash
  when: current_node.stdout == "none"

- name: update npm
  shell: source {{ node.nvm_bin }}; npm install -g npm@~3.3.8 chdir={{ project_dir }} executable=/bin/bash
  when: current_node.stdout == "none" and node.update_npm

- name: install packages
  shell: source {{ node.nvm_bin }}; npm install chdir={{ working_dir }} executable=/bin/bash
