<?php
return array(
	'BE' => array(
		'compressionLevel' => '0',
		'disable_exec_function' => '0',
		'flexformForceCDATA' => '1',
		'installToolPassword' => '${security.install_tool_password}',
		'loginSecurityLevel' => 'rsa',
		'maxFileSize' => '50000',
		'versionNumberInFilename' => '0',
	),
	'DB' => array(
		'database' => '${database.name}',
		'extTablesDefinitionScript' => 'extTables.php',
		'host' => '${database.host}',
		'password' => '${database.password}',
		'port' => ${database.port},
		'username' => '${database.username}',
	),
	'EXT' => array(
		'allowGlobalInstall' => '0',
		'extConf' => array(
			'beautyofcode' => 'a:1:{s:15:"enable_t3editor";s:1:"1";}',
			'css_styled_content' => 'a:2:{s:15:"setPageTSconfig";s:1:"1";s:19:"removePositionTypes";s:1:"1";}',
			'dbmigrate' => 'a:0:{}',
			'disqusapi' => 'a:0:{}',
			'em' => 'a:4:{s:14:"showOldModules";s:1:"0";s:14:"inlineToWindow";s:1:"1";s:19:"displayMyExtensions";s:1:"1";s:17:"selectedLanguages";s:2:"de";}',
			'filemetadata' => 'a:0:{}',
			'fluidcontent' => 'a:1:{s:9:"removeTab";s:1:"1";}',
			'fluidcontent_core' => 'a:0:{}',
			'fluidpages' => 'a:3:{s:8:"autoload";s:1:"1";s:8:"doktypes";s:2:"30";s:10:"autoRender";s:1:"0";}',
			'flux' => 'a:4:{s:9:"debugMode";s:1:"${TYPO3_CONF_VARS.EXT.extConf.flux.debugMode}";s:7:"compact";s:1:"0";s:20:"rewriteLanguageFiles";s:1:"0";s:12:"handleErrors";s:1:"0";}',
			'form4_pages_rss' => 'a:1:{s:16:"form4_pages_rss.";a:6:{s:23:"excludedDoktypeInSelect";s:17:"6,7,3,199,254,255";s:13:"sortingFields";s:84:"title,subtitle,crdate,lastUpdated,uid,starttime,endtime,newUntil,author,author_email";s:8:"encoding";s:5:"utf-8";s:8:"maxitems";s:2:"10";s:10:"image_maxW";s:3:"300";s:10:"image_maxH";s:3:"150";}}',
			'lowlevel' => 'a:0:{}',
			'mediace' => 'a:0:{}',
			'opendocs' => 'a:1:{s:12:"enableModule";s:1:"0";}',
			'realurl' => 'a:5:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"0";s:14:"autoConfFormat";s:1:"0";s:12:"enableDevLog";s:1:"0";s:19:"enableChashUrlDebug";s:1:"0";}',
			'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:53:"/kunden/199447_70794/rp-hosting/7367/8368/rsaauth-tmp";}',
			'saltedpasswords' => 'a:2:{s:3:"FE.";a:2:{s:7:"enabled";s:1:"1";s:21:"saltedPWHashingMethod";s:28:"tx_saltedpasswords_salts_md5";}s:3:"BE.";a:1:{s:21:"saltedPWHashingMethod";s:28:"tx_saltedpasswords_salts_md5";}}',
			'sbo' => 'a:0:{}',
			'secret_santa' => 'a:0:{}',
			'static_info_tables' => 'a:4:{s:13:"enableManager";s:1:"0";s:5:"dummy";s:1:"0";s:7:"charset";s:5:"utf-8";s:12:"usePatch1822";s:1:"0";}',
			'static_info_tables_de' => 'a:1:{s:5:"dummy";s:1:"0";}',
			't3jquery' => 'a:14:{s:15:"alwaysIntegrate";s:1:"0";s:17:"integrateToFooter";s:1:"0";s:17:"enableStyleStatic";s:1:"0";s:18:"dontIntegrateOnUID";s:0:"";s:23:"dontIntegrateInRootline";s:0:"";s:13:"jqLibFilename";s:23:"jquery-###VERSION###.js";s:9:"configDir";s:19:"uploads/tx_t3jquery";s:13:"jQueryVersion";s:5:"1.8.x";s:15:"jQueryUiVersion";s:5:"1.9.x";s:18:"jQueryTOOLSVersion";s:0:"";s:22:"jQueryBootstrapVersion";s:0:"";s:16:"integrateFromCDN";s:1:"0";s:11:"locationCDN";s:6:"jquery";s:13:"updateMessage";s:1:"0";}',
			'tstemplate_analyzer' => 'a:0:{}',
			'tstemplate_objbrowser' => 'a:0:{}',
			'vantomas' => 'a:1:{s:6:"pages.";a:1:{s:9:"abstract.";a:1:{s:4:"rte.";a:3:{s:15:"disableGlobally";s:1:"1";s:11:"showButtons";s:103:"bold, italic, left, center, right, orderedlist, unorderedlist, outdent, indent, insertcharacter, chMode";s:11:"hideButtons";s:606:"class, blockstylelabel, blockstyle, textstylelabel, textstyle, formatblock, subscript, superscript, textindicator, link, table, findreplace, removeformat, undo, redo, about, toggleborders, tableproperties, rowproperties, rowinsertabove, rowinsertunder, rowdelete, rowsplit, columninsertbefore, columninsertafter, columndelete, columnsplit, cellproperties, cellinsertbefore, cellinsertafter, celldelete, cellsplit, cellmerge, chMode, blockstyle, textstyle, underline, strikethrough, subscript, superscript, lefttoright, righttoleft, justifyfull, table, inserttag, findreplace, removeformat, copy, cut, paste";}}}}',
			'vhs' => 'a:0:{}',
		),
	),
	'EXTCONF' => array(
		'lang' => array(
			'availableLanguages' => array(
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'de',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
			),
		),
	),
	'FE' => array(
		'compressionLevel' => '5',
		'disableNoCacheParameter' => '0',
		'lockIP' => '4',
		'noPHPscriptInclude' => '1',
		'pageNotFound_handling' => 'http://www.van-tomas.de/page-not-found/index.html',
		'permalogin' => '0',
		'versionNumberInFilename' => 'embed',
	),
	'GFX' => array(
		'colorspace' => 'RGB',
		'gdlib_png' => '1',
		'gif_compress' => '0',
		'im' => '1',
		'im_mask_temp_ext_gif' => '1',
		'im_noScaleUp' => '1',
		'im_path' => '/usr/bin/',
		'im_path_lzw' => '/usr/bin/',
		'im_v5effects' => '-1',
		'im_version_5' => 'gm',
		'image_processing' => '1',
		'imagefile_ext' => 'gif,jpg,jpeg,tif,bmp,pcx,tga,png,pdf,ai',
		'jpg_quality' => '85',
		'png_truecolor' => '1',
		'thumbnails_png' => '1',
	),
	'INSTALL' => array(
		'wizardDone' => array(
			'TYPO3\CMS\Install\CoreUpdates\CompressionLevelUpdate' => 1,
			'TYPO3\CMS\Install\CoreUpdates\InstallSysExtsUpdate' => '["info","perm","func","filelist","about","cshmanual","feedit","opendocs","recycler","t3editor","reports","scheduler","simulatestatic"]',
			'TYPO3\CMS\Install\Updates\BackendUserStartModuleUpdate' => 1,
			'TYPO3\CMS\Rtehtmlarea\Hook\Install\DeprecatedRteProperties' => 1,
			'TYPO3\CMS\Rtehtmlarea\Hook\Install\RteAcronymButtonRenamedToAbbreviation' => 1,
			'tx_coreupdates_installnewsysexts' => '1',
			'tx_rtehtmlarea_deprecatedRteProperties' => '1',
		),
	),
	'SYS' => array(
		'UTF8filesystem' => '0',
		'binPath' => '${TYPO3_CONF_VARS.SYS.binPath}',
		'caching' => array(
			'cacheConfigurations' => array(
				'extbase_object' => array(
					'backend' => '${TYPO3_CONF_VARS.SYS.caching.cacheConfigurations.extbase_object.backend}',
					'frontend' => 'TYPO3\\CMS\\Core\\Cache\\Frontend\\VariableFrontend',
					'groups' => array(
						'system',
					),
					'options' => array(
						'defaultLifetime' => 0,
					),
				),
			),
		),
		'clearCacheSystem' => '1',
		'curlUse' => '1',
		'debugExceptionHandler' => '${TYPO3_CONF_VARS.SYS.debugExceptionHandler}',
		'devIPmask' => '',
		'displayErrors' => '-1',
		'enableDeprecationLog' => '${TYPO3_CONF_VARS.SYS.enableDeprecationLog}',
		'enable_DLOG' => '1',
		'enable_errorDLOG' => '0',
		'encryptionKey' => '${security.encryption.key}',
		'errorHandler' => 'TYPO3\\CMS\\Core\\Error\\ErrorHandler',
		'exceptionalErrors' => '28917',
		'productionExceptionHandler' => '${TYPO3_CONF_VARS.SYS.productionExceptionHandler}',
		'sitename' => '${TYPO3_CONF_VARS.SYS.sitename}',
		'sqlDebug' => '0',
		'systemLog' => '${TYPO3_CONF_VARS.SYS.systemLog}',
		'systemLogLevel' => '${TYPO3_CONF_VARS.SYS.systemLogLevel}',
		't3lib_cs_convMethod' => 'mbstring',
		't3lib_cs_utils' => 'mbstring',
	),
);
?>