---

php_packages:
  - php5-fpm
  - php5
  - php5-cli
  - php5-curl
  - php5-gd
  - php5-json
  - php5-mcrypt
  - php5-mysql
  - php5-sqlite
  - php5-xdebug
  - php5-xsl
  - php5-apcu
  - php5-intl

php_configuration:
  - { src: "etc/php5/cli/conf.d/01-php.ini", dest: "/etc/php5/cli/conf.d" }
  - { src: "etc/php5/cli/conf.d/21-apcu.ini", dest: "/etc/php5/cli/conf.d" }
  - { src: "etc/php5/fpm/conf.d/00-php.ini", dest: "/etc/php5/fpm/conf.d" }
  - { src: "etc/php5/fpm/conf.d/06-opcache.ini", dest: "/etc/php5/fpm/conf.d" }
  - { src: "etc/php5/fpm/conf.d/21-apcu.ini", dest: "/etc/php5/fpm/conf.d" }
  - { src: "etc/php5/fpm/conf.d/21-xdebug.ini", dest: "/etc/php5/fpm/conf.d" }
  - { src: "etc/php5/fpm/pool.d/vagrant.conf", dest: "/etc/php5/fpm/pool.d" }
