---

- name: install nginx
  apt: name=nginx update_cache=yes cache_valid_time={{ provision_apt_update_cache_cache_valid_time }}

- name: remove default host
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx

- name: add custom host
  template: src=etc/nginx/sites-enabled/00-vagrant dest=/etc/nginx/sites-enabled
  notify:
    - restart nginx

- name: add additional configuration
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items: "{{ nginx_configuration }}"
  notify:
    - restart nginx

- name: check configuration
  command: nginx -t
