---

- name: install nginx
  apt: name=nginx update_cache=yes cache_valid_time={{ provision.apt.update_cache.cache_valid_time }}

- name: remove default host
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx

- name: add custom host + additional configuration
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items: "{{ nginx.configuration }}"
  notify:
    - restart nginx
