<?php
//return include_once(dirname(__FILE__) . '/../../../../vendor/composer/autoload_classmap.php');

$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('vantomas');

return array(
	'Net_Http' => $extensionPath . '../../../../vendor/net/http/src/Net/Http.php',
	'Net_Http_Client' => $extensionPath . '../../../../vendor/net/http/src/Net/Http/Client.php',
	'Net_Http_ClientError' => $extensionPath . '../../../../vendor/net/http/src/Net/Http/ClientError.php',
	'Net_Http_Exception' => $extensionPath . '../../../../vendor/net/http/src/Net/Http/Exception.php',
	'Net_Http_NetworkError' => $extensionPath . '../../../../vendor/net/http/src/Net/Http/NetworkError.php',
	'Net_Http_ProtocolError' => $extensionPath . '../../../../vendor/net/http/src/Net/Http/ProtocolError.php',
	'Net_Http_Request' => $extensionPath . '../../../../vendor/net/http/src/Net/Http/Request.php',
	'Net_Http_Response' => $extensionPath . '../../../../vendor/net/http/src/Net/Http/Response.php',
	'Net_Http_ServerError' => $extensionPath . '../../../../vendor/net/http/src/Net/Http/ServerError.php',
	'Illuminate\\Support\\Contracts\\ArrayableInterface' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Contracts/ArrayableInterface.php',
	'Illuminate\\Support\\Contracts\\JsonableInterface' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Contracts/JsonableInterface.php',
	'Illuminate\\Support\\Contracts\\MessageProviderInterface' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Contracts/MessageProviderInterface.php',
	'Illuminate\\Support\\Contracts\\RenderableInterface' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Contracts/RenderableInterface.php',
	'Illuminate\\Support\\Contracts\\ResponsePreparerInterface' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Contracts/ResponsePreparerInterface.php',
	'Illuminate\\Support\\Facades\\App' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/App.php',
	'Illuminate\\Support\\Facades\\Artisan' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Artisan.php',
	'Illuminate\\Support\\Facades\\Auth' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Auth.php',
	'Illuminate\\Support\\Facades\\Blade' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Blade.php',
	'Illuminate\\Support\\Facades\\Cache' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Cache.php',
	'Illuminate\\Support\\Facades\\Config' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Config.php',
	'Illuminate\\Support\\Facades\\Cookie' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Cookie.php',
	'Illuminate\\Support\\Facades\\Crypt' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Crypt.php',
	'Illuminate\\Support\\Facades\\DB' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/DB.php',
	'Illuminate\\Support\\Facades\\Event' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Event.php',
	'Illuminate\\Support\\Facades\\Facade' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Facade.php',
	'Illuminate\\Support\\Facades\\File' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/File.php',
	'Illuminate\\Support\\Facades\\Form' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Form.php',
	'Illuminate\\Support\\Facades\\Hash' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Hash.php',
	'Illuminate\\Support\\Facades\\HTML' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/HTML.php',
	'Illuminate\\Support\\Facades\\Input' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Input.php',
	'Illuminate\\Support\\Facades\\Lang' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Lang.php',
	'Illuminate\\Support\\Facades\\Log' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Log.php',
	'Illuminate\\Support\\Facades\\Mail' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Mail.php',
	'Illuminate\\Support\\Facades\\Paginator' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Paginator.php',
	'Illuminate\\Support\\Facades\\Password' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Password.php',
	'Illuminate\\Support\\Facades\\Queue' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Queue.php',
	'Illuminate\\Support\\Facades\\Redirect' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Redirect.php',
	'Illuminate\\Support\\Facades\\Redis' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Redis.php',
	'Illuminate\\Support\\Facades\\Request' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Request.php',
	'Illuminate\\Support\\Facades\\Response' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Response.php',
	'Illuminate\\Support\\Facades\\Route' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Route.php',
	'Illuminate\\Support\\Facades\\Schema' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Schema.php',
	'Illuminate\\Support\\Facades\\Session' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Session.php',
	'Illuminate\\Support\\Facades\\SSH' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/SSH.php',
	'Illuminate\\Support\\Facades\\URL' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/URL.php',
	'Illuminate\\Support\\Facades\\Validator' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/Validator.php',
	'Illuminate\\Support\\Facades\\View' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Facades/View.php',
	'Illuminate\\Support\\Collection' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Collection.php',
	'Illuminate\\Support\\Fluent' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Fluent.php',
	'Illuminate\\Support\\Manager' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Manager.php',
	'Illuminate\\Support\\MessageBag' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/MessageBag.php',
	'Illuminate\\Support\\NamespacedItemResolver' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/NamespacedItemResolver.php',
	'Illuminate\\Support\\Pluralizer' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Pluralizer.php',
	'Illuminate\\Support\\SerializeableClosure' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/SerializableClosure.php',
	'Illuminate\\Support\\ServiceProvider' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/ServiceProvider.php',
	'Illuminate\\Support\\Str' => $extensionPath . '../../../../vendor/illuminate/support/Illuminate/Support/Str.php',
	'Arg\\Tagcloud\\Tagcloud' => $extensionPath . '../../../../vendor/arg/tagcloud/src/Arg/Tagcloud/Tagcloud.php',
	'Arg\\Tagcloud\\TagcloudServiceProvider' => $extensionPath . '../../../../vendor/arg/tagcloud/src/Arg/Tagcloud/TagcloudServiceProvider.php',
);
?>