---

- name: generate pdepend report
  shell: xsltproc ./.ansible/xslt/{{ qa_reports_pdepend }}.xslt ./build/jdepend.xml > ./build/jdepend.html chdir={{ working_dir }} executable=/bin/bash
  when: qa_run_reports

- name: generate phpcpd report
  shell: xsltproc ./.ansible/xslt/{{ qa_reports_phpcpd }}.xslt ./build/phpcpd.xml > ./build/phpcpd.html chdir={{ working_dir }} executable=/bin/bash
  when: qa_run_reports

- name: generate checkstyle report
  shell: xsltproc ./.ansible/xslt/{{ qa_reports_phpcs }}.xslt ./build/phpcs-checkstyle.xml > ./build/phpcs-checkstyle.html chdir={{ working_dir }} executable=/bin/bash
  when: qa_run_reports
